[2022-08-24T20:07:37.402+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: xcom_dag.inaccurate manual__2022-08-24T20:07:34.124980+00:00 [queued]>
[2022-08-24T20:07:37.409+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: xcom_dag.inaccurate manual__2022-08-24T20:07:34.124980+00:00 [queued]>
[2022-08-24T20:07:37.411+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-08-24T20:07:37.412+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-08-24T20:07:37.413+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-08-24T20:07:37.421+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): inaccurate> on 2022-08-24 20:07:34.124980+00:00
[2022-08-24T20:07:37.426+0000] {standard_task_runner.py:52} INFO - Started process 25521 to run task
[2022-08-24T20:07:37.429+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 'inaccurate', 'manual__2022-08-24T20:07:34.124980+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmppmn63clt', '--error-file', '/tmp/tmp_lr9qirw']
[2022-08-24T20:07:37.430+0000] {standard_task_runner.py:80} INFO - Job 39: Subtask inaccurate
[2022-08-24T20:07:37.476+0000] {task_command.py:371} INFO - Running <TaskInstance: xcom_dag.inaccurate manual__2022-08-24T20:07:34.124980+00:00 [running]> on host 9ab687ae92a7
[2022-08-24T20:07:37.520+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-24T20:07:34.124980+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-24T20:07:34.124980+00:00
[2022-08-24T20:07:37.522+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-24T20:07:37.524+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2022-08-24T20:07:37.533+0000] {subprocess.py:85} INFO - Output:
[2022-08-24T20:07:37.535+0000] {subprocess.py:92} INFO - inaccurate
[2022-08-24T20:07:37.536+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-24T20:07:37.556+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=xcom_dag, task_id=inaccurate, execution_date=20220824T200734, start_date=20220824T200737, end_date=20220824T200737
[2022-08-24T20:07:37.603+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-24T20:07:37.625+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
