[2022-08-24T19:29:55.554+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: xcom_dag.choose_best_model manual__2022-08-24T19:29:53.585562+00:00 [queued]>
[2022-08-24T19:29:55.562+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: xcom_dag.choose_best_model manual__2022-08-24T19:29:53.585562+00:00 [queued]>
[2022-08-24T19:29:55.563+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-08-24T19:29:55.565+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-08-24T19:29:55.566+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-08-24T19:29:55.574+0000] {taskinstance.py:1389} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2022-08-24 19:29:53.585562+00:00
[2022-08-24T19:29:55.579+0000] {standard_task_runner.py:52} INFO - Started process 23352 to run task
[2022-08-24T19:29:55.581+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 'choose_best_model', 'manual__2022-08-24T19:29:53.585562+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmphnqpvky8', '--error-file', '/tmp/tmpo76n_fj7']
[2022-08-24T19:29:55.583+0000] {standard_task_runner.py:80} INFO - Job 14: Subtask choose_best_model
[2022-08-24T19:29:55.630+0000] {task_command.py:371} INFO - Running <TaskInstance: xcom_dag.choose_best_model manual__2022-08-24T19:29:53.585562+00:00 [running]> on host 9ab687ae92a7
[2022-08-24T19:29:55.679+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=choose_best_model
AIRFLOW_CTX_EXECUTION_DATE=2022-08-24T19:29:53.585562+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-24T19:29:53.585562+00:00
[2022-08-24T19:29:55.681+0000] {logging_mixin.py:115} INFO - choose best model
[2022-08-24T19:29:55.691+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/xcom_dag.py", line 16, in _choose_best_model
    best_accuracy = max(accuracies)
ValueError: max() arg is an empty sequence
[2022-08-24T19:29:55.717+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=xcom_dag, task_id=choose_best_model, execution_date=20220824T192953, start_date=20220824T192955, end_date=20220824T192955
[2022-08-24T19:29:55.725+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task choose_best_model (max() arg is an empty sequence; 23352)
[2022-08-24T19:29:55.754+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-24T19:29:55.790+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
